steps:
# this yaml file should be manged by Terraform (like this PoC)
# OR should be manually added to each repo with the image tag being "stable" or "latest"
# this allows the build image to be very flexible and low-maintence
- name: gcr.io/ox-registry-prod/test/app:latest
  id: package
  # entrypoint: mvn
  args: ['mvn', 'package','-Dmaven.test.skip=true']

- name: gcr.io/ox-registry-prod/test/app:latest
  id: deploy
  entrypoint: mvn
  # skipTests for PoC speed
  args: ['deploy', '-Dmaven.skipTests=true']
  waitFor:
  # would be package or test for PR builds
    - deploy
